workflow:
    - main-without-template

jobs:
    main:
        template: node/test@1-stable

    main-without-template:
        image: node:6
        steps:
            - install: npm install
            - test: npm test
